actung_app/config/routes.rb
ActungApp::Application.routes.draw do
  devise_for :users

  resources :users
  resources :locations

  root to: 'locations#index'
end

actung_app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :admin
      can :manage, :all
    else
      can :create, Location
      can :read, Location
    end
  end
end

actung_app/app/models/location.rb
class Location < ActiveRecord::Base
  validates :lat, presence: true
  validates :lng, presence: true
  validates :user_id, presence: true
  
  attr_accessible :lat, :lng, :user_id

  belongs_to :user

  validate :user_quota, :on => :create

  def user_quota
    if user.locations.today.count >= 10
      errors.add(:base, "Exceeds daily limit")
    elsif  user.locations.this_week.count >= 30
      errors.add(:base, "Exceeds weekly limit")
    end
  end  
end

actung_app/app/models/user.rb
class User < ActiveRecord::Base
  before_validation :set_default_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role
  # validates :email, presence: true, uniquness: true

  has_many :locations do
    def today
      where(:created_at => (Time.now.beginning_of_day..Time.now))
    end

    def this_week
      where(:created_at => (Time.now.beginning_of_week..Time.now))
    end
  end

  def role?(role)
    self.role.to_s == role.to_s
  end

  private
  def set_default_role
    self.role ||= "user"
  end

end

actung_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url , alert: "You can't access this page"
  end
end

actung_app/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource
  
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create

    if request.xhr?
      @location = Location.new
      @location.lat = params['lat'].to_f
      @location.lng = params['lng'].to_f
      @location.user = current_user
    else
      @location = Location.new(params[:location])
      @location.user = current_user
    end
    
    respond_to do |format|
      if @location.save
        
        if request.xhr?
          
          format.json { render json: @location}
        else
          format.html { redirect_to locations_path }
        end
      else
        flash.now[:alert] = 'You have exceeded your daily quota!'
        format.html { redirect_to locations_url }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

actung_app/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_destroy_path_for(resource)
    root_path
  end

end

actung_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

actung_app/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

actung_app/app/helpers/locations_helper.rb
module LocationsHelper
end

actung_app/app/helpers/users_helper.rb
module UsersHelper
end

actung_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= (yield(:title).empty? ? "Achtung Kontrolleur!" : yield(:title) ) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,900,700,500,300,100' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAb9m-F6MB2kjwyl5GmuTUwsKra3MT2SBI&sensor=false"></script>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" name="apple-mobile-web-app-capable" content="width=device-width; initial-scale=1.0; user-scalable=no">
  <%= csrf_meta_tags %>
</head>
  <body>
    <div id='container'>

      <div id='topbar'>
        <%= link_to image_tag("logo.svg", :alt => "logo", :id => "logo"), root_path %>
        <span id='topname'>
          <% if current_user %>
            <%= "ACHTUNG! #{current_user.name.upcase}!" %>
          <% else %>
            <%= "ACHTUNG! KONTROLLEUR!" %>
          <% end %>
        </span>
        <span id='logout'>
          <% if current_user %>
            <%= link_to "LOGOUT!", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to logout?'} %>
          <% end %>
        </span>
      </div>

  
      <%= yield %>

      
      <div id='bottombar'>        
        <% if current_user %>
          <%= link_to image_tag("achtung.svg", :alt => "achtung", :id => "achtungbutton"), new_location_path, :id => "achtungbuttonlink" %>
        <% else %>
          <div id='sessionsbar'>
            <% unless content_for?(:bottombar) %>
              <%= render('devise/sessions/new.html.erb') %>
            <% end %>
            <%= yield(:bottombar) %>
          </div>
        <% end %>
        <% if current_user %>
          <div class='links'>
            <%= link_to 'About', page_path('about') %>
            &nbsp
            <%= link_to 'Legal', page_path('legal') %>
            &nbsp
            <%= link_to 'Contact', page_path('contact') %>
          </div>
        <% else %>
          <div class='links' id='loggedoutlinks'>
            <%= link_to 'About', page_path('about') %>
            &nbsp
            <%= link_to 'Legal', page_path('legal') %>
            &nbsp
            <%= link_to 'Contact', page_path('contact') %>
          </div>
        <% end %>
      </div>
      
    </div>
  </body>
</html>

actung_app/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

actung_app/app/views/locations/index.html.erb
<% if current_user %>
  <div id='map-canvas'>

  </div>
<% else %>
  <%= render 'pages/home' %>
<% end %>

actung_app/app/views/locations/new.html.erb
<%= render 'form' %>

actung_app/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>User:</b>
  <%= @location.user.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.lat %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.lng %>
</p>

<p>
  <b>Created at:</b>
  <%= @location.created_at %>
</p>

actung_app/app/views/pages/_home.html.erb
<div id="homepage">
  <%= image_tag("home.gif", :alt => "home", :id => "homegif") %>
</div>

actung_app/app/views/pages/about.html.erb
<%= content_for :title, "About" %>

<div class='pages'>
  <h1>ABOUT!</h1>
  <p id="legal">The idea for <span class="ak">Achtung! Kontrolleur!</span> was born from the paralysing anxiety that accompanies riding Berlin's public transport system without a validated ticket in contast fear of the undercover ticket inspector.
  <br>
  <br>
  Check <span class="ak">Achtung! Kontrolleur!</span> to see if there have been any ticket inspector sightings have occured recently between where you currently are and where you are wanting to go.
  <br>
  <br>
  If there is, buy a ticket.
  <br>
  <br>
  If not, relax and take a chance.
  <br>
  <br>
  If you see an inspector, let your fellow bahn-dits know by pressing the 'ACHTUNG!' button.
</div>

actung_app/app/views/pages/contact.html.erb
<%= content_for :title, "Contact" %>

<div class='pages'>
  <h1>CONTACT!</h1>
  <p id="legal">
    Get in touch!
    <br>
    <br>
    We would love to hear your feedback, feature suggestions and tales of narrow escapes from the inspectors.
    <br>
    <br>
    info@achtungkontrolleur.com
    <br>
    <br>
    Safe travels!
  </p>
</div>

actung_app/app/views/pages/legal.html.erb
<%= content_for :title, "Legal" %>

<div class='pages'>
  <h1>LEGAL!</h1>
  <p id="legal">
    <span id="one">
      <span class="ak">Achtung! Kontrolleur!</span> is not responsible for any fines for riding without a validated ticket.<br>
    </span>
    <span id="two">
      <span class="ak">Achtung! Kontrolleur!</span> is not responsible for any fines for riding without a validated ticket.<br>
    </span>
    <span id="three">
      <span class="ak">Achtung! Kontrolleur!</span> is not responsible for any fines for riding without a validated ticket.<br>
    </span>
    <span id="four">
      <span class="ak">Achtung! Kontrolleur!</span> is not responsible for any fines for riding without a validated ticket.<br>
    </span>
  </p>
</div>

actung_app/app/views/users/index.html.erb
<div class="adminform">
  <table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td class="namecell"><%= user.name %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
</div>